pool:
  vmImage: "windows-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "install"
      workingDir: $(System.DefaultWorkingDirectory)

  - task: Npm@1
    displayName: "npm run build"
    inputs:
      command: "custom"
      workingDir: $(System.DefaultWorkingDirectory)
      customCommand: run build

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)/dist"
      Contents: "**"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
